(()=>{'use strict';
const D=window.PLANNER_DATA,canvas=document.querySelector('#canvas'),ctx=canvas.getContext('2d');
const OX=78,OY=48,S=.94,STORE='centimetre-room-studio-v2';
let items=[],measurements=[],plans=[],activePlanId=null,selected=null,selectedIds=new Set(),selectedMeasurement=null,tool='select',drag=null,measureStart=null,measureHover=null,dropPreview=null,paletteDragKey=null,showGrid=true,showClear=true,showProximity=true,currentTemplate='2j',uid=1,history=[],historyIndex=-1;
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)],round=n=>Math.round(n*10)/10,clone=o=>JSON.parse(JSON.stringify(o));
function id(){return`item-${Date.now().toString(36)}-${uid++}`}
function clearSelection(){selected=null;selectedIds.clear();selectedMeasurement=null}
function setOnlySelected(itemId){selected=itemId;selectedIds=new Set(itemId?[itemId]:[]);selectedMeasurement=null}
function ensureMeasurementIds(){measurements.forEach(m=>m.id??=`measure-${Date.now().toString(36)}-${uid++}`)}
function selectedItems(){return items.filter(i=>selectedIds.has(i.id))}
function selectionBox(){let list=selectedItems();if(!list.length)return null;let bs=list.map(box),x=Math.min(...bs.map(b=>b.x)),y=Math.min(...bs.map(b=>b.y)),r=Math.max(...bs.map(b=>b.x+b.w)),bt=Math.max(...bs.map(b=>b.y+b.d));return{x,y,w:r-x,d:bt-y}}
function fromPrefab(p,x=(D.room.width-p.w)/2,y=(D.room.length-p.d)/2){return{id:id(),name:p.name,x:round(x),y:round(y),w:p.w,d:p.d,h:p.h||0,shape:p.shape||'rect',leg:p.leg||null,color:p.color||'#d8cfb7',rot:0,clearance:p.clearance||0,seats:p.seats||0,round:p.round||3,note:p.note||''}}
function fromTemplate(a){if(!Array.isArray(a))return{...clone(a),id:id()};return{id:id(),name:a[0],x:a[1],y:a[2],w:a[3],d:a[4],h:a[5],shape:a[6],color:a[7],rot:a[8]||0,leg:a[9]||null,clearance:a[10]||0,seats:a[11]||0,round:4,note:''}}
function rawRotate(px,py,rot){let a=rot*Math.PI/180,c=Math.cos(a),s=Math.sin(a);return[px*c-py*s,px*s+py*c]}
function rotationBounds(w,d,rot){let ps=[[0,0],[w,0],[w,d],[0,d]].map(p=>rawRotate(p[0],p[1],rot)),xs=ps.map(p=>p[0]),ys=ps.map(p=>p[1]);return{minX:Math.min(...xs),minY:Math.min(...ys),w:Math.max(...xs)-Math.min(...xs),d:Math.max(...ys)-Math.min(...ys)}}
function orientedDims(i){let b=rotationBounds(i.w,i.d,i.rot);return[round(b.w),round(b.d)]}
function box(i){const [w,d]=orientedDims(i);return{x:i.x,y:i.y,w,d}}
function localPoints(i){if(i.shape==='l-right'){let l=Math.min(i.leg||Math.min(i.w,i.d),i.w,i.d);return[[i.w-l,0],[i.w,0],[i.w,i.d],[0,i.d],[0,i.d-l],[i.w-l,i.d-l]]}if(i.shape==='l-left'){let l=Math.min(i.leg||Math.min(i.w,i.d),i.w,i.d);return[[0,0],[l,0],[l,i.d-l],[i.w,i.d-l],[i.w,i.d],[0,i.d]]}return[[0,0],[i.w,0],[i.w,i.d],[0,i.d]]}
function points(i){let bounds=rotationBounds(i.w,i.d,i.rot);return localPoints(i).map(([a,b])=>{let p=rawRotate(a,b,i.rot);return[i.x+p[0]-bounds.minX,i.y+p[1]-bounds.minY]})}
function rotateRect(r,w,d,rot){if(rot===90)return{x:d-r.y-r.d,y:r.x,w:r.d,d:r.w};if(rot===180)return{x:w-r.x-r.w,y:d-r.y-r.d,w:r.w,d:r.d};if(rot===270)return{x:r.y,y:w-r.x-r.w,w:r.d,d:r.w};return r}
function parts(i){if(i.rot%90!==0)return[box(i)];let raw;if(i.shape==='l-right'){let l=i.leg;raw=[{x:0,y:i.d-l,w:i.w,d:l},{x:i.w-l,y:0,w:l,d:i.d}]}else if(i.shape==='l-left'){let l=i.leg;raw=[{x:0,y:i.d-l,w:i.w,d:l},{x:0,y:0,w:l,d:i.d}]}else raw=[{x:0,y:0,w:i.w,d:i.d}];return raw.map(r=>{let q=rotateRect(r,i.w,i.d,i.rot);return{x:i.x+q.x,y:i.y+q.y,w:q.w,d:q.d}})}
const overlap=(a,b,eps=.001)=>a.x<b.x+b.w-eps&&a.x+a.w>b.x+eps&&a.y<b.y+b.d-eps&&a.y+a.d>b.y+eps;
const itemOverlap=(a,b)=>{if((a.onTopOf&&a.onTopOf===b.supportKey)||(b.onTopOf&&b.onTopOf===a.supportKey))return false;return parts(a).some(pa=>parts(b).some(pb=>overlap(pa,pb)))};
function supported(i){return!!i.onTopOf&&items.some(o=>o.supportKey===i.onTopOf&&overlap(box(i),box(o)))}
function pointInPoly(p,poly){let c=false;for(let a=0,b=poly.length-1;a<poly.length;b=a++){let A=poly[a],B=poly[b];if(((A[1]>p.y)!==(B[1]>p.y))&&p.x<(B[0]-A[0])*(p.y-A[1])/(B[1]-A[1])+A[0])c=!c}return c}
function canvasPoint(e){const r=canvas.getBoundingClientRect(),sx=canvas.width/r.width,sy=canvas.height/r.height;return{x:round(((e.clientX-r.left)*sx-OX)/S),y:round(((e.clientY-r.top)*sy-OY)/S)}}
function hit(p){for(let n=items.length-1;n>=0;n--){let i=items[n];if(i.shape==='circle'){let b=box(i),dx=p.x-b.x-b.w/2,dy=p.y-b.y-b.d/2;if(dx*dx+dy*dy<=(b.w/2)**2)return i.id}else if(pointInPoly(p,points(i)))return i.id}return null}
function fixedRects(){return[...D.fixed.kitchen,...D.fixed.radiators,D.fixed.divider]}
function collisionIds(){let ids=new Set;items.forEach((a,n)=>{if(parts(a).some(p=>fixedRects().some(f=>overlap(p,f))))ids.add(a.id);items.slice(n+1).forEach(b=>{if(itemOverlap(a,b)){ids.add(a.id);ids.add(b.id)}})});return ids}
function activePlan(){return plans.find(p=>p.id===activePlanId)}
function readOnly(){return!!activePlan()?.locked}
function requireEditable(){if(!readOnly())return true;alert('This is a read-only default. Use Duplicate plan to make an editable copy.');return false}
function updateReadOnlyUI(){let locked=readOnly();for(const selector of['#import','#reset','#rename-plan','#rotate','#rotate90','#duplicate','#delete','#delete-measurement','#clear-measures','[data-tool="measure"]']){let el=$(selector);if(el)el.disabled=locked}$('#close-plan').disabled=locked||plans.length<=1;$('#selection-form').querySelectorAll('input,select,button').forEach(el=>el.disabled=locked);for(const selector of['#custom-form button','#jattebo-form button']){let el=$(selector);if(el)el.disabled=locked}let status=$('#plan-status');if(status){status.textContent=locked?'Read-only default · Duplicate plan to edit':'Editable plan · Autosaves in this browser';status.classList.toggle('locked',locked)}if(locked&&tool==='measure'){tool='select';measureStart=null;measureHover=null;canvas.classList.remove('measure');$$('[data-tool]').forEach(b=>b.classList.toggle('active',b.dataset.tool==='select'))}}
function syncPlan(){let p=activePlan();if(!p||p.locked)return;p.items=items;p.measurements=measurements;p.template=currentTemplate}
function makePlan(name,sourceItems=[],sourceMeasures=[],template='custom',locked=false){return{id:`plan-${Date.now().toString(36)}-${uid++}`,name,items:clone(sourceItems),measurements:clone(sourceMeasures),template,baseTemplate:template,locked}}
function defaultPlans(){let templates=D.templates.filter(t=>t.locked);if(!templates.length)templates=[D.templates[0]];return templates.map(t=>{let p=makePlan(t.name,t.items.map(fromTemplate),[],t.id,!!t.locked);p.id=`default-${t.id}`;p.items.forEach((i,n)=>i.id=`${p.id}-item-${n}`);return p})}
function withDefaults(existing){let defaults=defaultPlans(),byId=new Map(defaults.map(p=>[p.id,p])),seen=new Set(existing.map(p=>p.id));return[...defaults.filter(p=>!seen.has(p.id)),...existing.filter(p=>!p.locked||byId.has(p.id)).map(p=>byId.get(p.id)||p)]}
function freshWorkspace(){plans=defaultPlans();let p=plans[0];activePlanId=p.id;items=p.items;measurements=p.measurements;currentTemplate=p.template;clearSelection();commit()}
function snapshot(){syncPlan();return JSON.stringify({plans,activePlanId})}
function commit(){const s=snapshot();if(history[historyIndex]===s)return;history=history.slice(0,historyIndex+1);history.push(s);historyIndex=history.length-1;localStorage.setItem(STORE,s);updateHistoryButtons();renderPlanTabs()}
function restore(s){let v=JSON.parse(s);if(Array.isArray(v.plans)){plans=withDefaults(v.plans);activePlanId=v.activePlanId||plans[0]?.id}else{let recovered=makePlan('Recovered plan',v.items||[],v.measurements||[],v.currentTemplate||'custom');plans=withDefaults([recovered]);activePlanId=recovered.id}let p=activePlan()||plans[0];activePlanId=p?.id;items=p?.items||[];measurements=p?.measurements||[];currentTemplate=p?.template||'custom';clearSelection();renderPlanTabs();draw()}
function undo(){if(historyIndex>0){historyIndex--;restore(history[historyIndex]);localStorage.setItem(STORE,history[historyIndex]);updateHistoryButtons()}}
function redo(){if(historyIndex<history.length-1){historyIndex++;restore(history[historyIndex]);localStorage.setItem(STORE,history[historyIndex]);updateHistoryButtons()}}
function updateHistoryButtons(){$('#undo').disabled=historyIndex<=0;$('#redo').disabled=historyIndex>=history.length-1}
function loadTemplate(t,record=true){if(!requireEditable())return;currentTemplate=t.id;items=t.items.map(fromTemplate);measurements=[];clearSelection();let p=activePlan();if(p){p.items=items;p.measurements=measurements;p.template=t.id;p.name=t.name}if(record)commit();renderPlanTabs();draw()}
function switchPlan(planId){syncPlan();let p=plans.find(v=>v.id===planId);if(!p)return;activePlanId=p.id;items=p.items;measurements=p.measurements;currentTemplate=p.template||'custom';clearSelection();measureStart=null;localStorage.setItem(STORE,snapshot());renderPlanTabs();draw()}
function reorderPlan(dragId,targetId,after=false){if(!dragId||dragId===targetId)return;syncPlan();let from=plans.findIndex(p=>p.id===dragId),moving=plans[from];if(from<0||!moving||moving.locked)return;plans.splice(from,1);let target=plans.findIndex(p=>p.id===targetId);if(target<0)plans.push(moving);else plans.splice(target+(after?1:0),0,moving);commit();renderPlanTabs()}
function clearTabDropStyles(){$$('.plan-tab').forEach(t=>t.classList.remove('dragging','drop-before','drop-after'))}
function renderPlanTabs(){let root=$('#plan-tabs');if(!root)return;root.innerHTML='';plans.forEach(p=>{let b=document.createElement('button');b.className=`plan-tab ${p.id===activePlanId?'active':''} ${p.locked?'locked':''}`;b.textContent=p.name;b.title=p.locked?'Read-only default · Duplicate plan to edit':'Drag to reorder · double-click to rename';b.draggable=!p.locked;b.dataset.planId=p.id;b.onclick=()=>switchPlan(p.id);b.ondblclick=()=>renamePlan(p.id);b.ondragstart=e=>{e.dataTransfer.effectAllowed='move';e.dataTransfer.setData('text/plan',p.id);requestAnimationFrame(()=>b.classList.add('dragging'))};b.ondragover=e=>{e.preventDefault();e.dataTransfer.dropEffect='move';$$('.plan-tab').forEach(t=>t.classList.remove('drop-before','drop-after'));let after=e.clientX>b.getBoundingClientRect().left+b.offsetWidth/2;b.classList.add(after?'drop-after':'drop-before')};b.ondrop=e=>{e.preventDefault();let dragId=e.dataTransfer.getData('text/plan'),after=e.clientX>b.getBoundingClientRect().left+b.offsetWidth/2;clearTabDropStyles();reorderPlan(dragId,p.id,after)};b.ondragend=clearTabDropStyles;root.append(b)});root.ondragover=e=>{if(e.target===root)e.preventDefault()};root.ondrop=e=>{if(e.target!==root)return;e.preventDefault();let dragId=e.dataTransfer.getData('text/plan');clearTabDropStyles();let moving=plans.find(p=>p.id===dragId);if(moving&&!moving.locked&&plans.at(-1)!==moving){plans=plans.filter(p=>p.id!==dragId);plans.push(moving);commit();renderPlanTabs()}};updateReadOnlyUI()}
function renamePlan(planId=activePlanId){let p=plans.find(v=>v.id===planId);if(!p)return;if(p.locked)return alert('Default plans cannot be renamed. Duplicate this plan first.');let name=prompt('Plan name',p.name);if(name&&name.trim()){p.name=name.trim();commit();renderPlanTabs()}}
function duplicatePlan(){syncPlan();let p=activePlan(),copy=makePlan(`${p.name} copy`,p.items,p.measurements,p.template);copy.baseTemplate=p.baseTemplate||p.template;copy.items.forEach(i=>i.id=id());plans.push(copy);activePlanId=copy.id;items=copy.items;measurements=copy.measurements;currentTemplate=copy.template;clearSelection();commit();draw()}
function newBlankPlan(){syncPlan();let p=makePlan(`Plan ${plans.length+1}`,[],[],'blank');plans.push(p);activePlanId=p.id;items=p.items;measurements=p.measurements;currentTemplate='blank';clearSelection();commit();draw()}
function closePlan(){if(readOnly())return;if(plans.length<=1)return;let p=activePlan();if(!confirm(`Close “${p.name}”?`))return;let index=plans.indexOf(p);plans.splice(index,1);let next=plans[Math.min(index,plans.length-1)];activePlanId=next.id;items=next.items;measurements=next.measurements;currentTemplate=next.template;clearSelection();commit();draw()}
function screenRect(r){return{x:OX+r.x*S,y:OY+r.y*S,w:r.w*S,h:r.d*S}}
function rounded(r,fill,stroke='#35574a',dash=[]){let q=screenRect(r);ctx.save();ctx.fillStyle=fill;ctx.strokeStyle=stroke;ctx.lineWidth=1.6;ctx.setLineDash(dash);ctx.beginPath();ctx.roundRect(q.x,q.y,q.w,q.h,Math.min(7,q.w/4,q.h/4));ctx.fill();ctx.stroke();ctx.restore()}
function text(t,x,y,color='#29483b',size=9,align='center'){ctx.fillStyle=color;ctx.font=`600 ${size}px DM Mono`;ctx.textAlign=align;ctx.fillText(t,OX+x*S,OY+y*S)}
function drawArchitecture(){ctx.fillStyle='#fffdf8';ctx.fillRect(OX,OY,D.room.width*S,D.room.length*S);if(showGrid){for(let n=0;n<=D.room.width;n+=10){ctx.strokeStyle=n%50===0?'#ddd9cc':'#eeece4';ctx.lineWidth=n%50===0?.8:.35;ctx.beginPath();ctx.moveTo(OX+n*S,OY);ctx.lineTo(OX+n*S,OY+D.room.length*S);ctx.stroke()}for(let n=0;n<=D.room.length;n+=10){ctx.strokeStyle=n%50===0?'#ddd9cc':'#eeece4';ctx.lineWidth=n%50===0?.8:.35;ctx.beginPath();ctx.moveTo(OX,OY+n*S);ctx.lineTo(OX+D.room.width*S,OY+n*S);ctx.stroke()}}
 D.fixed.kitchen.forEach((r,n)=>{rounded(r,'#acb991','#47634e');if(!n)text('FIXED KITCHEN',105,478,'#fff',9)});rounded(D.fixed.divider,'#405a4d','#30483d');D.fixed.radiators.forEach(r=>rounded(r,'#dfbc67','#ba9135'));D.fixed.windows.forEach(r=>{ctx.strokeStyle='#5d9caf';ctx.lineWidth=6;ctx.beginPath();ctx.moveTo(OX+515*S,OY+r.y*S);ctx.lineTo(OX+515*S,OY+(r.y+r.d)*S);ctx.stroke()});
 ctx.strokeStyle='#294b3d';ctx.lineWidth=5;ctx.strokeRect(OX,OY,D.room.width*S,D.room.length*S);ctx.strokeStyle='#d16e42';ctx.lineWidth=6;ctx.setLineDash([7,5]);ctx.beginPath();ctx.moveTo(OX,OY+170*S);ctx.lineTo(OX,OY+250*S);ctx.stroke();ctx.setLineDash([]);rounded(D.fixed.arrival,'#ffffff08','#d16e42',[6,5]);text('HALL 80',8,215,'#a35e3c',9,'left');text('515 cm',257.5,-14,'#9a6246',10);ctx.save();ctx.translate(OX-25,OY+360*S);ctx.rotate(-Math.PI/2);ctx.fillStyle='#9a6246';ctx.font='600 10px DM Mono';ctx.textAlign='center';ctx.fillText('721 cm nominal',0,0);ctx.restore()}
function clearanceObstacles(excludeId){let owner=items.find(i=>i.id===excludeId)?.clearanceKey;return items.filter(o=>o.id!==excludeId&&!supported(o)&&!(owner&&o.clearanceOwner===owner)).map(o=>({...box(o),name:o.name})).concat(fixedRects().map(o=>({...o,name:o.id||'fixed architecture'})))}
function availableFromEdge(b,side,obstacles){let horizontal=side==='north'||side==='south',available=side==='north'?b.y:side==='south'?D.room.length-b.y-b.d:side==='west'?b.x:D.room.width-b.x-b.w;for(const o of obstacles){let crosses=horizontal?o.x<b.x+b.w&&o.x+o.w>b.x:o.y<b.y+b.d&&o.y+o.d>b.y;if(!crosses)continue;let gap=null;if(side==='north'&&o.y+o.d<=b.y)gap=b.y-o.y-o.d;else if(side==='south'&&o.y>=b.y+b.d)gap=o.y-b.y-b.d;else if(side==='west'&&o.x+o.w<=b.x)gap=b.x-o.x-o.w;else if(side==='east'&&o.x>=b.x+b.w)gap=o.x-b.x-b.w;if(gap!==null)available=Math.min(available,gap)}return Math.max(0,round(available))}
function clearanceBands(i){if(!i.clearance&&!i.seats)return[];let b=box(i),obstacles=clearanceObstacles(i.id),rot=((i.rot%360)+360)%360,sides=rot%90===0?(rot%180?['west','east']:['north','south']):['north','east','south','west'];return sides.map(side=>{let available=availableFromEdge(b,side,obstacles),depth=Math.max(92,Math.min(152,Math.floor(available))),band=side==='north'?{x:b.x,y:b.y-depth,w:b.w,d:depth}:side==='south'?{x:b.x,y:b.y+b.d,w:b.w,d:depth}:side==='west'?{x:b.x-depth,y:b.y,w:depth,d:b.d}:{x:b.x+b.w,y:b.y,w:depth,d:b.d};return{...band,side,available,depth,short:available<92,capped:available>152}})}
function drawItem(i,collisions,forceSelected=false){if(showClear)clearanceBands(i).forEach(b=>{let fill=b.short?'#d96b5033':'#e8c66b2e',stroke=b.short?'#c84f3b':'#b98522';rounded(b,fill,stroke,[6,4]);text(`${b.depth} cm${b.capped?' MAX':''}`,b.x+b.w/2,b.y+b.d/2,b.short?'#b33f2d':'#9a711f',8)});let poly=points(i),isSel=forceSelected||selectedIds.has(i.id),b=box(i);ctx.save();ctx.fillStyle=i.color;ctx.strokeStyle=collisions.has(i.id)?'#c54f3c':isSel?'#d16e42':'#35574a';ctx.lineWidth=isSel?3:1.6;ctx.beginPath();if(i.shape==='circle'){let q=screenRect(b);ctx.ellipse(q.x+q.w/2,q.y+q.h/2,q.w/2,q.h/2,0,0,Math.PI*2)}else{poly.forEach((p,n)=>{let X=OX+p[0]*S,Y=OY+p[1]*S;n?ctx.lineTo(X,Y):ctx.moveTo(X,Y)});ctx.closePath()}ctx.fill();ctx.stroke();ctx.restore();
 if(i.shape.startsWith('l-')){parts(i).forEach((p,n)=>{if(n){ctx.strokeStyle='#56766a';ctx.lineWidth=1;let q=screenRect(p);ctx.strokeRect(q.x,q.y,q.w,q.h)}})}
 let label=i.name.length>28?i.name.slice(0,26)+'…':i.name;text(label,b.x+b.w/2,b.y+b.d/2,'#263f35',Math.min(9,Math.max(7,b.w*S/18)));if(isSel){ctx.save();ctx.strokeStyle='#d16e42';ctx.lineWidth=1;ctx.setLineDash([4,3]);let q=screenRect(b);ctx.strokeRect(q.x-4,q.y-4,q.w+8,q.h+8);ctx.restore();text(`${round(b.w)} × ${round(b.d)} cm`,b.x+b.w/2,b.y-7,'#b65736',9)}}
function drawMeasures(){measurements.forEach((m,n)=>drawMeasure(m,`${n+1}`,m.id===selectedMeasurement));if(tool==='measure'&&measureStart&&measureHover)drawMeasure({a:measureStart,b:measureHover},'live',false)}
function drawMeasure(m,label,isSelected=false){let {a,b}=m,ax=OX+a.x*S,ay=OY+a.y*S,bx=OX+b.x*S,by=OY+b.y*S,dist=Math.hypot(b.x-a.x,b.y-a.y);ctx.save();ctx.strokeStyle=isSelected?'#e04f27':'#bd5537';ctx.fillStyle=isSelected?'#e04f27':'#bd5537';ctx.lineWidth=isSelected?4:2;ctx.setLineDash(isSelected?[]:[6,4]);ctx.beginPath();ctx.moveTo(ax,ay);ctx.lineTo(bx,by);ctx.stroke();ctx.setLineDash([]);for(const [X,Y] of [[ax,ay],[bx,by]]){ctx.beginPath();ctx.arc(X,Y,isSelected?6:4,0,Math.PI*2);ctx.fill()}ctx.font='600 10px DM Mono';ctx.textAlign='center';let tx=(ax+bx)/2,ty=(ay+by)/2-7;ctx.fillStyle='#fffdf8';ctx.fillRect(tx-39,ty-11,78,15);ctx.fillStyle=isSelected?'#d23f1b':'#9d442e';ctx.fillText(`${round(dist)} cm`,tx,ty);ctx.restore()}
function pointSegmentDistance(p,a,b){let vx=b.x-a.x,vy=b.y-a.y,len=vx*vx+vy*vy;if(!len)return Math.hypot(p.x-a.x,p.y-a.y);let t=Math.max(0,Math.min(1,((p.x-a.x)*vx+(p.y-a.y)*vy)/len)),x=a.x+t*vx,y=a.y+t*vy;return Math.hypot(p.x-x,p.y-y)}
function hitMeasurement(p){for(let n=measurements.length-1;n>=0;n--)if(pointSegmentDistance(p,measurements[n].a,measurements[n].b)<=8)return measurements[n].id;return null}
function proximityObstacles(excluded=selectedIds){return items.filter(i=>!excluded.has(i.id)&&!supported(i)).flatMap(i=>parts(i).map((p,n)=>({...p,name:i.name,part:n}))).concat(fixedRects().map(f=>({...f,name:f.id||'fixed architecture'})))}
function proximityRays(b,excluded=selectedIds){let obs=proximityObstacles(excluded),right=b.x+b.w,bottom=b.y+b.d,defaults={west:{side:'west',gap:b.x,name:'left wall',a:{x:b.x,y:b.y+b.d/2},b:{x:0,y:b.y+b.d/2}},east:{side:'east',gap:D.room.width-right,name:'right wall',a:{x:right,y:b.y+b.d/2},b:{x:D.room.width,y:b.y+b.d/2}},north:{side:'north',gap:b.y,name:'top wall',a:{x:b.x+b.w/2,y:b.y},b:{x:b.x+b.w/2,y:0}},south:{side:'south',gap:D.room.length-bottom,name:'bottom wall',a:{x:b.x+b.w/2,y:bottom},b:{x:b.x+b.w/2,y:D.room.length}}};for(const o of obs){let oRight=o.x+o.w,oBottom=o.y+o.d,vertical=Math.min(bottom,oBottom)-Math.max(b.y,o.y),horizontal=Math.min(right,oRight)-Math.max(b.x,o.x);if(vertical>0&&oRight<=b.x){let gap=b.x-oRight,y=(Math.max(b.y,o.y)+Math.min(bottom,oBottom))/2;if(gap<defaults.west.gap)defaults.west={side:'west',gap,name:o.name,a:{x:b.x,y},b:{x:oRight,y}}}if(vertical>0&&o.x>=right){let gap=o.x-right,y=(Math.max(b.y,o.y)+Math.min(bottom,oBottom))/2;if(gap<defaults.east.gap)defaults.east={side:'east',gap,name:o.name,a:{x:right,y},b:{x:o.x,y}}}if(horizontal>0&&oBottom<=b.y){let gap=b.y-oBottom,x=(Math.max(b.x,o.x)+Math.min(right,oRight))/2;if(gap<defaults.north.gap)defaults.north={side:'north',gap,name:o.name,a:{x,y:b.y},b:{x,y:oBottom}}}if(horizontal>0&&o.y>=bottom){let gap=o.y-bottom,x=(Math.max(b.x,o.x)+Math.min(right,oRight))/2;if(gap<defaults.south.gap)defaults.south={side:'south',gap,name:o.name,a:{x,y:bottom},b:{x,y:o.y}}}}return Object.values(defaults)}
function rayFromAnchor(anchor,side,excluded){let obs=proximityObstacles(excluded),r=side==='west'?{side,gap:anchor.x,name:'left wall',a:anchor,b:{x:0,y:anchor.y}}:side==='east'?{side,gap:D.room.width-anchor.x,name:'right wall',a:anchor,b:{x:D.room.width,y:anchor.y}}:side==='north'?{side,gap:anchor.y,name:'top wall',a:anchor,b:{x:anchor.x,y:0}}:{side,gap:D.room.length-anchor.y,name:'bottom wall',a:anchor,b:{x:anchor.x,y:D.room.length}};for(const o of obs){let oRight=o.x+o.w,oBottom=o.y+o.d,gap=null,end=null;if((side==='west'||side==='east')&&anchor.y>=o.y&&anchor.y<=oBottom){if(side==='west'&&oRight<=anchor.x){gap=anchor.x-oRight;end={x:oRight,y:anchor.y}}else if(side==='east'&&o.x>=anchor.x){gap=o.x-anchor.x;end={x:o.x,y:anchor.y}}}else if((side==='north'||side==='south')&&anchor.x>=o.x&&anchor.x<=oRight){if(side==='north'&&oBottom<=anchor.y){gap=anchor.y-oBottom;end={x:anchor.x,y:oBottom}}else if(side==='south'&&o.y>=anchor.y){gap=o.y-anchor.y;end={x:anchor.x,y:o.y}}}if(gap!==null&&gap<r.gap)r={side,gap,name:o.name,a:anchor,b:end}}return r}
function polygonProximityRays(item,excluded){if(item.rot%90!==0)return proximityRays(box(item),excluded);let poly=points(item),rays=[];for(let n=0;n<poly.length;n++){let a=poly[n],b=poly[(n+1)%poly.length],dx=b[0]-a[0],dy=b[1]-a[1],anchor={x:(a[0]+b[0])/2,y:(a[1]+b[1])/2},side;if(Math.abs(dx)<.01){let west={x:anchor.x-.2,y:anchor.y},east={x:anchor.x+.2,y:anchor.y};side=!pointInPoly(west,poly)&&pointInPoly(east,poly)?'west':'east'}else if(Math.abs(dy)<.01){let north={x:anchor.x,y:anchor.y-.2},south={x:anchor.x,y:anchor.y+.2};side=!pointInPoly(north,poly)&&pointInPoly(south,poly)?'north':'south'}else continue;rays.push(rayFromAnchor(anchor,side,excluded))}return rays}
function drawProximityGuides(group=selectionBox(),excluded=selectedIds,shapeItem=null){if(!group)return;let one=shapeItem||(selectedItems().length===1?selectedItems()[0]:null),rays=one?.shape.startsWith('l-')?polygonProximityRays(one,excluded):proximityRays(group,excluded);rays.forEach(r=>{let ax=OX+r.a.x*S,ay=OY+r.a.y*S,bx=OX+r.b.x*S,by=OY+r.b.y*S,mx=(ax+bx)/2,my=(ay+by)/2,label=`${round(r.gap)} cm · ${r.name.length>18?r.name.slice(0,17)+'…':r.name}`,horizontal=r.side==='west'||r.side==='east';ctx.save();ctx.strokeStyle=r.gap<0?'#c84f3b':'#2782a0';ctx.fillStyle=ctx.strokeStyle;ctx.lineWidth=1.8;ctx.setLineDash([4,3]);ctx.beginPath();ctx.moveTo(ax,ay);ctx.lineTo(bx,by);ctx.stroke();ctx.setLineDash([]);for(const [X,Y] of [[ax,ay],[bx,by]]){ctx.beginPath();if(horizontal){ctx.moveTo(X,Y-5);ctx.lineTo(X,Y+5)}else{ctx.moveTo(X-5,Y);ctx.lineTo(X+5,Y)}ctx.stroke()}ctx.font='600 9px DM Mono';let tw=ctx.measureText(label).width+10;ctx.fillStyle='#fffdf8eF';ctx.fillRect(mx-tw/2,my-15,tw,13);ctx.fillStyle=r.gap<0?'#b43e2c':'#216d86';ctx.textAlign='center';ctx.fillText(label,mx,my-5);ctx.restore()})}
function draw(){updateReadOnlyUI();ensureMeasurementIds();ctx.clearRect(0,0,canvas.width,canvas.height);ctx.fillStyle='#f4f1e7';ctx.fillRect(0,0,canvas.width,canvas.height);drawArchitecture();let collisions=collisionIds();items.forEach(i=>drawItem(i,collisions));if(drag&&showProximity)drawProximityGuides();if(dropPreview){drawItem(dropPreview,new Set(),true);if(showProximity)drawProximityGuides(box(dropPreview),new Set(),dropPreview)}drawMeasures();renderInspector();renderMeasurements();renderChecks(collisions)}
function renderInspector(){let list=selectedItems(),i=items.find(v=>v.id===selected)||list[0],m=measurements.find(v=>v.id===selectedMeasurement),form=$('#selection-form'),measurePanel=$('#measurement-selection');$('#selection-empty').hidden=!!i||!!m;form.hidden=!i;measurePanel.hidden=!m;let note=$('#item-note');if(note)note.textContent=i?.note||'';if(m){let dx=Math.abs(m.b.x-m.a.x),dy=Math.abs(m.b.y-m.a.y),dist=Math.hypot(dx,dy);$('#measurement-details').innerHTML=`Length <b>${round(dist)} cm</b><br>Δx ${round(dx)} cm · Δy ${round(dy)} cm<br>A (${m.a.x}, ${m.a.y})<br>B (${m.b.x}, ${m.b.y})`;$('#distances').innerHTML=`Selected measurement: <b>${round(dist)} cm</b>`;return}if(!i){$('#distances').textContent='Select furniture.';return}selected=i.id;$('#selection-count').innerHTML=list.length>1?`<b>${list.length} items selected.</b> Editing fields below changes the primary item; move, rotate, duplicate and delete affect the whole group.`:'1 item selected.';for(const k of['name','x','y','w','d','h','rot','leg','color']){let el=form.elements[k];if(!el)continue;if(document.activeElement!==el)el.value=i[k]??''}form.elements.leg.disabled=readOnly()||!i.shape.startsWith('l-');let b=selectionBox(),walls={Left:b.x,Top:b.y,Right:D.room.width-b.x-b.w,Bottom:D.room.length-b.y-b.d},nearest=null;items.filter(v=>!selectedIds.has(v.id)).forEach(v=>{let q=box(v),dx=Math.max(q.x-(b.x+b.w),b.x-(q.x+q.w),0),dy=Math.max(q.y-(b.y+b.d),b.y-(q.y+q.d),0),dist=Math.hypot(dx,dy);if(!nearest||dist<nearest.dist)nearest={name:v.name,dist}});$('#distances').innerHTML=`${list.length>1?`<p>Combined selection: <b>${round(b.w)} × ${round(b.d)} cm</b></p>`:''}<div class="distance-grid">${Object.entries(walls).map(([k,v])=>`<span>${k}: <b>${round(v)} cm</b></span>`).join('')}</div>${nearest?`<p>Nearest object: <b>${nearest.name}</b> · ${round(nearest.dist)} cm</p>`:''}`;if(i.seats){let bands=clearanceBands(i);$('#distances').innerHTML+=`<p><b>Adaptive dining boundaries</b><br>${bands.map(v=>`${v.side}: ${v.depth} cm${v.short?` (only ${v.available} cm available — below minimum)`:v.capped?' (capped at maximum)':''}`).join('<br>')}</p>`}}
function renderMeasurements(){let el=$('#measurements');if(!measurements.length){el.textContent=tool==='measure'?(measureStart?'Choose the second point.':'Click the first point.'):'Choose Measure, then click two points.';return}el.innerHTML=measurements.map((m,n)=>{let dx=Math.abs(m.b.x-m.a.x),dy=Math.abs(m.b.y-m.a.y),active=m.id===selectedMeasurement?' active':'';return`<div class="measure-row${active}" data-measure="${m.id}"><b>${n+1}. ${round(Math.hypot(dx,dy))} cm</b><button type="button" class="measure-delete" data-delete-measure="${m.id}">×</button><br>Δx ${round(dx)} · Δy ${round(dy)}<br>(${m.a.x}, ${m.a.y}) → (${m.b.x}, ${m.b.y})</div>`}).join('');el.querySelectorAll('[data-measure]').forEach(row=>row.onclick=e=>{if(e.target.closest('[data-delete-measure]'))return;clearSelection();selectedMeasurement=row.dataset.measure;draw()});el.querySelectorAll('[data-delete-measure]').forEach(b=>b.onclick=e=>{e.stopPropagation();deleteMeasurement(b.dataset.deleteMeasure)})}
function renderChecks(collisions){let issues=[];items.forEach(i=>{let b=box(i);if(b.x<0||b.y<0||b.x+b.w>D.room.width||b.y+b.d>D.room.length)issues.push(`${i.name} leaves the room`);if(parts(i).some(p=>fixedRects().some(f=>overlap(p,f))))issues.push(`${i.name} intersects fixed architecture`);if(parts(i).some(p=>overlap(p,D.fixed.arrival))&&!/desk chair/i.test(i.name))issues.push(`${i.name} enters hall arrival`);D.fixed.windows.forEach(w=>{let strip={x:475,y:w.y,w:40,d:w.d};if(parts(i).some(p=>overlap(p,strip)))issues.push(`${i.name} enters ${w.id} access strip`)})});items.forEach((a,n)=>items.slice(n+1).forEach(b=>{if(itemOverlap(a,b))issues.push(`${a.name} overlaps ${b.name}`)}));items.filter(i=>i.clearance||i.seats).forEach(i=>clearanceBands(i).forEach(b=>{if(b.short)issues.push(`${i.name} has only ${b.available} cm on ${b.side}; minimum is 92 cm`);if(b.x<0||b.y<0||b.x+b.w>D.room.width||b.y+b.d>D.room.length)issues.push(`${i.name} ${b.side} minimum boundary leaves room`);items.filter(o=>o.id!==i.id&&!supported(o)&&!(i.clearanceKey&&o.clearanceOwner===i.clearanceKey)).forEach(o=>{if(parts(o).some(p=>overlap(p,b)))issues.push(`${i.name} ${b.side} boundary hits ${o.name}`)});if(fixedRects().some(f=>overlap(f,b)))issues.push(`${i.name} ${b.side} boundary hits fixed architecture`)}));issues=[...new Set(issues)];$('#checks').innerHTML=issues.length?issues.map(v=>`<div class="check warn">● ${v}</div>`).join(''):'<div class="check pass">● No modelled collisions</div><div class="check pass">● All objects inside nominal room</div>';}
function setTool(t){if(t==='measure'&&!requireEditable())return;tool=t;measureStart=null;measureHover=null;$$('[data-tool]').forEach(b=>b.classList.toggle('active',b.dataset.tool===t));canvas.classList.toggle('measure',t==='measure');draw()}
function addPrefab(p,at){if(!requireEditable())return;let i=fromPrefab(p,at?at.x-p.w/2:undefined,at?at.y-p.d/2:undefined);i.x=Math.round(i.x);i.y=Math.round(i.y);items.push(i);setOnlySelected(i.id);currentTemplate='custom';commit();draw()}
function deleteMeasurement(measureId=selectedMeasurement){if(!requireEditable())return;if(!measureId)return;measurements=measurements.filter(m=>m.id!==measureId);if(selectedMeasurement===measureId)selectedMeasurement=null;commit();draw()}
function deleteSelected(){if(!requireEditable())return;if(selectedMeasurement){deleteMeasurement();return}if(!selectedIds.size)return;items=items.filter(i=>!selectedIds.has(i.id));clearSelection();commit();draw()}
function rotateSelected(degrees=45){if(!requireEditable())return;let list=selectedItems();if(!list.length)return;let group=selectionBox(),cx=group.x+group.w/2,cy=group.y+group.d/2,a=degrees*Math.PI/180,c=Math.cos(a),s=Math.sin(a);list.forEach(i=>{let b=box(i),ix=b.x+b.w/2,iy=b.y+b.d/2,dx=ix-cx,dy=iy-cy,nx=cx+dx*c-dy*s,ny=cy+dx*s+dy*c;i.rot=(i.rot+degrees+360)%360;let [w,d]=orientedDims(i);i.x=round(nx-w/2);i.y=round(ny-d/2)});currentTemplate='custom';commit();draw()}
function duplicateSelected(){if(!requireEditable())return;let list=selectedItems();if(!list.length)return;let newIds=[];list.forEach(i=>{let q=clone(i);q.id=id();q.name+=' copy';q.x+=10;q.y+=10;items.push(q);newIds.push(q.id)});selectedIds=new Set(newIds);selected=newIds[0];currentTemplate='custom';commit();draw()}
function buildPalette(){let groups={};D.prefabs.forEach(p=>(groups[p.group]??=[]).push(p));let root=$('#prefabs');root.innerHTML='';Object.entries(groups).forEach(([g,list])=>{let sec=document.createElement('div');sec.className='prefab-group';sec.innerHTML=`<h3>${g}</h3>`;list.forEach(p=>{let b=document.createElement('button');b.className='prefab';b.draggable=true;b.dataset.key=p.key;b.innerHTML=`<span>${p.name}</span><small>${p.w}×${p.d}</small>`;b.ondragstart=e=>{paletteDragKey=p.key;e.dataTransfer.setData('text/prefab',p.key)};b.ondragend=()=>{paletteDragKey=null;dropPreview=null;draw()};b.ondblclick=()=>addPrefab(p);sec.append(b)});root.append(sec)});filterPalette()}
function filterPalette(){let q=$('#search').value.toLowerCase();$$('.prefab').forEach(b=>b.hidden=!b.textContent.toLowerCase().includes(q))}
function buildTemplates(){let root=$('#templates');D.templates.forEach(t=>{let b=document.createElement('button');b.className='template';b.textContent=t.name;b.onclick=()=>{if(t.locked)return switchPlan(`default-${t.id}`);if(!requireEditable())return;if(confirm(`Load ${t.name}? Current unsaved arrangement will be replaced.`))loadTemplate(t)};root.append(b)})}
function jatteboConfig(){let f=$('#jattebo-form'),n70=Math.max(0,Number(f.elements.n70.value)||0),n95=Math.max(0,Number(f.elements.n95.value)||0),chaise=f.elements.chaise.value,arms=f.elements.arms.value,armCount=arms==='both'?2:arms==='none'?0:1,w=n70*70+n95*95+(chaise==='none'?0:95)+armCount*25,d=chaise==='none'?95:160;return{n70,n95,chaise,arms,w,d}}
function updateJatteboSummary(){let c=jatteboConfig(),ok=c.w>0&&c.w<=330;$('#jattebo-summary').innerHTML=`Footprint: <b>${c.w} × ${c.d} cm</b><br>${c.n70} narrow + ${c.n95} wide module(s) · ${c.chaise==='none'?'no chaise':`${c.chaise} chaise`} · ${c.arms} arms${ok?'':'<br><b class="warn">Outside the 330 cm room-fitting catalog limit.</b>'}`}

canvas.onpointerdown=e=>{canvas.focus();let p=canvasPoint(e);if(tool==='measure'){if(!requireEditable())return;if(!measureStart){clearSelection();measureStart=p;measureHover=p}else{let m={id:`measure-${Date.now().toString(36)}-${uid++}`,a:measureStart,b:p};measurements.push(m);measureStart=null;measureHover=null;selectedMeasurement=m.id;commit()}draw();return}let measureTarget=hitMeasurement(p);if(measureTarget){clearSelection();selectedMeasurement=measureTarget;draw();return}selectedMeasurement=null;let target=hit(p);if(e.shiftKey){if(target){if(selectedIds.has(target)){selectedIds.delete(target);if(selected===target)selected=[...selectedIds].at(-1)||null}else{selectedIds.add(target);selected=target}}draw();return}if(!target){clearSelection();draw();return}if(!selectedIds.has(target))setOnlySelected(target);else selected=target;if(readOnly()){draw();return}drag={anchor:p,starts:selectedItems().map(i=>({id:i.id,x:i.x,y:i.y})),moved:false};canvas.setPointerCapture(e.pointerId);draw()};
canvas.onpointermove=e=>{let p=canvasPoint(e);$('#cursor').textContent=`x ${p.x} · y ${p.y}`;if(tool==='measure'&&measureStart){measureHover=p;draw();return}if(!drag)return;let dx=Math.round(p.x-drag.anchor.x),dy=Math.round(p.y-drag.anchor.y);drag.starts.forEach(v=>{let i=items.find(q=>q.id===v.id);if(i){i.x=v.x+dx;i.y=v.y+dy}});drag.moved=dx!==0||dy!==0;draw()};
canvas.onpointerup=()=>{if(drag?.moved){currentTemplate='custom';commit()}drag=null};canvas.onpointerleave=()=>{$('#cursor').textContent='x — · y —'};
canvas.ondragover=e=>{if(readOnly())return;e.preventDefault();let key=paletteDragKey||e.dataTransfer.getData('text/prefab'),p=D.prefabs.find(v=>v.key===key);if(!p)return;let at=canvasPoint(e);dropPreview={id:'drop-preview',name:p.name,x:Math.round(at.x-p.w/2),y:Math.round(at.y-p.d/2),w:p.w,d:p.d,h:p.h||0,shape:p.shape||'rect',leg:p.leg||null,color:p.color||'#d8cfb7',rot:0,clearance:p.clearance||0,seats:p.seats||0,round:p.round||3,note:p.note||''};draw()};canvas.ondragleave=e=>{if(!e.relatedTarget||!canvas.contains(e.relatedTarget)){dropPreview=null;draw()}};canvas.ondrop=e=>{e.preventDefault();if(!requireEditable())return;let key=paletteDragKey||e.dataTransfer.getData('text/prefab'),p=D.prefabs.find(v=>v.key===key),at=canvasPoint(e);dropPreview=null;paletteDragKey=null;if(p)addPrefab(p,at)};
window.addEventListener('keydown',e=>{if(['INPUT','TEXTAREA'].includes(document.activeElement.tagName))return;if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='z'){e.preventDefault();e.shiftKey?redo():undo();return}if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='y'){e.preventDefault();redo();return}if(e.key==='Escape'){measureStart=null;measureHover=null;clearSelection();setTool('select');return}if(readOnly())return;if(selectedMeasurement&&(e.key==='Delete'||e.key==='Backspace')){e.preventDefault();deleteMeasurement();return}let list=selectedItems();if(!list.length)return;let step=e.shiftKey?10:1,dx=0,dy=0;if(e.key==='ArrowLeft')dx=-step;else if(e.key==='ArrowRight')dx=step;else if(e.key==='ArrowUp')dy=-step;else if(e.key==='ArrowDown')dy=step;else if(e.key.toLowerCase()==='r'){e.preventDefault();rotateSelected(e.shiftKey?90:45);return}else if(e.key==='Delete'||e.key==='Backspace'){deleteSelected();return}else return;e.preventDefault();list.forEach(i=>{i.x+=dx;i.y+=dy});currentTemplate='custom';commit();draw()});
$$('[data-tool]').forEach(b=>b.onclick=()=>setTool(b.dataset.tool));$('#clear-measures').onclick=()=>{if(!requireEditable())return;measurements=[];measureStart=null;selectedMeasurement=null;commit();draw()};$('#grid').onclick=e=>{showGrid=!showGrid;e.target.classList.toggle('active',showGrid);draw()};$('#clearances').onclick=e=>{showClear=!showClear;e.target.classList.toggle('active',showClear);draw()};$('#live-gaps').onclick=e=>{showProximity=!showProximity;e.target.classList.toggle('active',showProximity);draw()};$('#delete-measurement').onclick=()=>deleteMeasurement();$('#undo').onclick=undo;$('#redo').onclick=redo;$('#rotate').onclick=()=>rotateSelected(45);$('#rotate90').onclick=()=>rotateSelected(90);$('#duplicate').onclick=duplicateSelected;$('#delete').onclick=deleteSelected;$('#search').oninput=filterPalette;
$('#selection-form').onchange=e=>{if(!requireEditable())return;let i=items.find(v=>v.id===selected);if(!i)return;let k=e.target.name;if(!k)return;i[k]=['name','color'].includes(k)?e.target.value:Number(e.target.value);if(k==='rot')i.rot=(Math.round(i.rot/45)*45+360)%360;if(k==='leg')i.leg=Math.min(i.leg,i.w,i.d);currentTemplate='custom';commit();draw()};
$('#jattebo-form').oninput=updateJatteboSummary;$('#jattebo-form').onsubmit=e=>{e.preventDefault();let c=jatteboConfig();if(c.w<=0)return alert('Add at least one seat or chaise module.');if(c.w>330&&!confirm(`${c.w} cm exceeds the room-fitting 330 cm catalog limit. Add anyway?`))return;let color=e.target.elements.color.value,shape=c.chaise==='none'?'rect':`l-${c.chaise}`,name=`JÄTTEBO ${c.w} × ${c.d} · ${c.chaise==='none'?'straight':`${c.chaise} chaise`} · arms ${c.arms}`,p={name,w:c.w,d:c.d,h:71,color,shape,leg:c.chaise==='none'?null:95,note:`${c.n70}×70 cm + ${c.n95}×95 cm modules; arms ${c.arms}.`};addPrefab(p)};updateJatteboSummary();
$('#custom-form').onsubmit=e=>{e.preventDefault();let f=new FormData(e.target),p={name:f.get('name'),w:Number(f.get('w')),d:Number(f.get('d')),h:Number(f.get('h')),color:f.get('color'),shape:'rect'};addPrefab(p)};
$('#new-plan').onclick=newBlankPlan;$('#duplicate-plan').onclick=duplicatePlan;$('#rename-plan').onclick=()=>renamePlan();$('#close-plan').onclick=closePlan;
$('#export').onclick=()=>{syncPlan();let p=activePlan(),payload={schema:'centimetre-room-studio-v2',units:'cm',room:D.room,plan:{id:p.id,name:p.name,items:p.items,measurements:p.measurements},workspacePlans:plans.map(v=>({id:v.id,name:v.name}))};let blob=new Blob([JSON.stringify(payload,null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`${p.name.toLowerCase().replace(/[^a-z0-9]+/g,'-')||'room-layout'}-cm.json`;a.click();URL.revokeObjectURL(a.href)};
$('#import').onchange=e=>{if(!requireEditable()){e.target.value='';return}let file=e.target.files[0];if(!file)return;let targetPlanId=activePlanId,r=new FileReader;r.onload=()=>{if(activePlanId!==targetPlanId||readOnly())return alert('Import cancelled because the selected plan changed.');try{let v=JSON.parse(r.result),src=v.plan||v;if(!Array.isArray(src.items))throw Error('No items array');items=src.items;measurements=src.measurements||[];clearSelection();currentTemplate='imported';let p=activePlan();p.items=items;p.measurements=measurements;p.template='imported';if(src.name)p.name=src.name;commit();draw()}catch(err){alert(`Could not import: ${err.message}`)}};r.readAsText(file);e.target.value=''};
$('#reset').onclick=()=>{if(!requireEditable())return;let p=activePlan(),t=D.templates.find(v=>v.id===(p.baseTemplate||currentTemplate))||D.templates.find(v=>v.id==='2j');if(confirm(`Reset to ${t.name}?`))loadTemplate(t)};
buildPalette();buildTemplates();let saved=localStorage.getItem(STORE);if(saved){try{restore(saved);history=[snapshot()];historyIndex=0;localStorage.setItem(STORE,history[0])}catch{freshWorkspace()}}else{freshWorkspace()}renderPlanTabs();updateHistoryButtons();draw();
})();